import React from 'react';
import { OrdersClientManager } from '@/components/admin/OrdersClientManager';
import { AdminOrderRecord } from '@/components/admin/OrderInspectionModal';

export const revalidate = 0;

export default async function AdminOrdersPage() {
  let orders: AdminOrderRecord[] = [
    {
      id: 'ord-101',
      orderNumber: 'SH-20260918-8472',
      createdAt: new Date().toISOString(),
      orderStatus: 'CONFIRMED',
      paymentStatus: 'PAID',
      paymentMethod: 'BKASH',
      orderSource: 'WEBSITE',
      customer: { name: 'Ahsanul Islam', email: 'ahsanul@gmail.com', mobile: '+880 1712-345678' },
      address: { recipient: 'Ahsanul Islam', phone: '+880 1712-345678', city: 'Dhaka', thana: 'Gulshan 2', street: 'House 14, Road 27, Block K', postalCode: '1212', district: 'Dhaka' },
      items: [
        {
          id: 'it-1',
          productName: 'Architectural Obsidian Tailored Suit',
          variantSku: 'SH-SUT-OBS-40R',
          color: 'Obsidian Jet Black',
          size: '40R',
          quantity: 1,
          unitPrice: 28500,
          totalPrice: 28500,
          imageUrl: '/images/products/architectural-black-suit-1.jpg',
        },
      ],
      subtotalBDT: 28500,
      discountBDT: 0,
      shippingFeeBDT: 0,
      totalBDT: 28500,
      courierName: 'Steadfast Courier',
      trackingNumber: 'STDF-84920194',
      customerNotes: 'Please ring bell twice upon arrival.',
      staffNotes: 'VIP Customer. Double layer tissue garment bag included.',
      fulfilmentStatus: 'PACKED',
    },
    {
      id: 'ord-102',
      orderNumber: 'SH-MAN-20260918-9321',
      createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
      orderStatus: 'SHIPPED',
      paymentStatus: 'PENDING',
      paymentMethod: 'COD',
      orderSource: 'WHATSAPP',
      customer: { name: 'Naveed Chowdhury', email: 'naveed@gmail.com', mobile: '+880 1711-889900' },
      address: { recipient: 'Naveed Chowdhury', phone: '+880 1711-889900', city: 'Dhaka', thana: 'Banani', street: 'House 34, Road 11, Block C', postalCode: '1213', district: 'Dhaka' },
      items: [
        {
          id: 'it-wh-1',
          productName: 'Raw Selvedge Denim Trucker Jacket',
          variantSku: 'SH-DNM-IND-L',
          color: 'Raw Deep Indigo',
          size: 'L',
          quantity: 1,
          unitPrice: 16500,
          totalPrice: 16500,
          imageUrl: '/images/products/raw-selvedge-trucker-jacket.jpg',
        },
      ],
      subtotalBDT: 16500,
      discountBDT: 500,
      shippingFeeBDT: 80,
      totalBDT: 16080,
      courierName: 'Pathao Courier',
      trackingNumber: 'PTH-9921048',
      dispatchedAt: new Date(Date.now() - 3600000).toISOString(),
      staffNotes: '[Channel: WHATSAPP] Customer requested urgent dispatch for evening event.',
      fulfilmentStatus: 'DISPATCHED',
    },
    {
      id: 'ord-103',
      orderNumber: 'SH-MAN-20260918-4512',
      createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
      orderStatus: 'PROCESSING',
      paymentStatus: 'PAID',
      paymentMethod: 'BKASH',
      orderSource: 'PHONE',
      transactionId: 'BK9948201',
      customer: { name: 'Tasnim Rahman', email: 'tasnim.r@outlook.com', mobile: '+880 1819-876543' },
      address: { recipient: 'Tasnim Rahman', phone: '+880 1819-876543', city: 'Dhaka', thana: 'Dhanmondi', street: 'Apt 4B, Road 7A', postalCode: '1209', district: 'Dhaka' },
      items: [
        {
          id: 'it-2',
          productName: 'Monolith Contrast-Collar Technical Polo',
          variantSku: 'SH-POL-BLK-M',
          color: 'Jet Black / Gold Trim',
          size: 'M',
          quantity: 2,
          unitPrice: 7800,
          totalPrice: 15600,
          imageUrl: '/images/products/monolith-contrast-polo.jpg',
        },
      ],
      subtotalBDT: 15600,
      discountBDT: 1000,
      shippingFeeBDT: 80,
      totalBDT: 14680,
      courierName: 'Steadfast Courier',
      trackingNumber: '',
      staffNotes: '[Channel: PHONE] Verified over phone call. bKash received.',
      fulfilmentStatus: 'PROCESSING',
    },
    {
      id: 'ord-104',
      orderNumber: 'SH-20260917-6523',
      createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
      orderStatus: 'DELIVERED',
      paymentStatus: 'PAID',
      paymentMethod: 'COD',
      orderSource: 'INSTAGRAM',
      customer: { name: 'Farhan Kabir', email: 'farhan.k@gmail.com', mobile: '+880 1911-223344' },
      address: { recipient: 'Farhan Kabir', phone: '+880 1911-223344', city: 'Chittagong', thana: 'GEC', street: 'Equity Tower, GEC Circle', postalCode: '4000', district: 'Chittagong' },
      items: [
        {
          id: 'it-4',
          productName: 'Tactical Cyber Kimono',
          variantSku: 'SH-KIM-BLK-L',
          color: 'Onyx Black',
          size: 'L',
          quantity: 1,
          unitPrice: 18500,
          totalPrice: 18500,
          imageUrl: '/images/products/architectural-black-suit-1.jpg',
        },
      ],
      subtotalBDT: 18500,
      discountBDT: 0,
      shippingFeeBDT: 150,
      totalBDT: 18650,
      courierName: 'Steadfast Courier',
      trackingNumber: 'STDF-65230911',
      dispatchedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
      deliveredAt: new Date(Date.now() - 3600000 * 2).toISOString(),
      fulfilmentStatus: 'DELIVERED',
    },
    {
      id: 'ord-105',
      orderNumber: 'SH-MAN-20260916-2189',
      createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
      orderStatus: 'CANCELLED',
      paymentStatus: 'REFUNDED',
      paymentMethod: 'BKASH',
      orderSource: 'FACEBOOK',
      cancellationReason: 'Customer unreachable / Phone switched off',
      cancelledAt: new Date(Date.now() - 3600000 * 40).toISOString(),
      isRestocked: true,
      customer: { name: 'Tanvir Hossain', email: 'tanvir@gmail.com', mobile: '+880 1715-001122' },
      address: { recipient: 'Tanvir Hossain', phone: '+880 1715-001122', city: 'Sylhet', thana: 'Zindabazar', street: 'House 5, Road 2, Subidbazar', postalCode: '3100', district: 'Sylhet' },
      items: [
        {
          id: 'it-5',
          productName: 'Architectural Obsidian Tailored Suit',
          variantSku: 'SH-SUT-OBS-42R',
          color: 'Obsidian Jet Black',
          size: '42R',
          quantity: 1,
          unitPrice: 28500,
          totalPrice: 28500,
          imageUrl: '/images/products/architectural-black-suit-1.jpg',
        },
      ],
      subtotalBDT: 28500,
      discountBDT: 0,
      shippingFeeBDT: 150,
      totalBDT: 28650,
      staffNotes: '[Channel: FACEBOOK] [CANCELLED: Customer unreachable / Phone switched off] [INVENTORY RESTOCKED: YES]',
      fulfilmentStatus: 'UNFULFILLED',
    },
  ];

  return (
    <div className="w-full">
      <OrdersClientManager initialOrders={orders} />
    </div>
  );
}
